<?php

/**
 * @file
 * Implements the SoftBank Payment Service for use with Drupal Commerce.
 */

// TODO: Implement hook_requirements to error if the default currency isnt JPY.

// TODO: Add unit tests to validate API functionality.

define('COMMERCE_SBPAYMENT_BASE_URL', 'commerce/sbpayment');
define('COMMERCE_SBPAYMENT_PAYMENT_METHOD', 'commerce_sbpayment');

/**
 * Implements hook_help().
 */
function commerce_sbpayment_help($path, $arg) {
  switch ($path) {
    case 'admin/help#commerce_sbpayment':
      $output = '<h2>' . t('Commerce SoftBank Payment Service') . '</h2>';
      $output .= '<p>' . t('Implements the SoftBank Payment Service for use with Drupal Commerce') . '<p>';

      return $output;
  }
}

/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_sbpayment_commerce_payment_method_info() {
  $payment_methods = array();

  $payment_methods[COMMERCE_SBPAYMENT_PAYMENT_METHOD] = array(
    'file' => 'includes/commerce_sbpayment.payment.inc',
    'title' => t('Commerce SoftBank Payment Service'),
    'description' => t('Redirect users to submit payments through the SoftBank Payment Service.'),
    'active' => (commerce_default_currency() === 'JPY'),
    'terminal' => FALSE,
    'offsite' => TRUE,
    'offsite_autoredirect' => TRUE,
  );

  return $payment_methods;
}

// TODO: Implement menu hook for CGI notification.

// TODO: Implement custom delivery callback for CGI notification.

/**
 * Get an array of default settings for the SoftBank Payment Service.
 *
 * @return array
 *   Array of default values keyed by field name.
 */
function commerce_sbpayment_default_settings() {
  return array(
    'mode' => \Commerce\SBPayment\SBPayment::API_MODE_TEST,
    'pay_methods' => array(),
    'merchant_id' => '',
    'service_id' => '',
    'pay_type' => 0,
    'auto_charge_type' => 0,
    'service_type' => 0,
    'hash_key' => '',
  );
}

/**
 * Get the available gateway mode options for use with the Drupal form API.
 *
 * @return string[]
 *   Array of gateway modes keyed by machine name.
 */
function _commerce_sbpayment_mode_options() {
  return array(
    \Commerce\SBPayment\SBPayment::API_MODE_TEST => t('Test'),
    \Commerce\SBPayment\SBPayment::API_MODE_LIVE => t('Live'),
  );
}

/**
 * Get a list of SoftBank payment methods for use with the Drupal form API.
 *
 * @param string[] $payment_methods
 *   List of the available payment method machine names as defined
 *   by Commerce\SBPayment\Payment\Methods.
 *
 * @return string[]
 *   Array of payment method names keyed by machine name.
 */
function _commerce_sbpayment_payment_method_options($payment_methods) {
  // Build an array of payment method names keyed by the machine name. Filtering
  // out any invalid methods.
  $payment_method_options = array_filter(array_map(function ($payment_method) {
    return \Commerce\SBPayment\Payment\Methods::getPaymentMethodByMachineName($payment_method);
  }, $payment_methods));

  // Allow other modules to alter the list of payment methods.
  drupal_alter('commerce_sbpayment_payment_method_options', $payment_method_options);

  return $payment_method_options;
}

// TODO: Add helper for saving transactions.
