<?php

/**
 * @file
 * Contains \Commerce\SBPayment\Response\LinkTypeCgi.
 */

namespace Commerce\SBPayment\Response;

/**
 * SoftBank response class for the 'Link Type' service CGI notification.
 */
class LinkTypeCgi implements ResponseInterface {

  /**
   * {@inheritdoc}
   */
  public function setResponseData(array $data) {}

  /**
   * {@inheritdoc}
   */
  public function getRemoteStatus() {}

  /**
   * {@inheritdoc}
   */
  public function __toString() {}

}
